services:
  - type: web
    name: trackflow-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: "PORT=$PORT npm run start"
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: "https://trackflow-jzex.onrender.com/api" 